const express = require("express");
const dotenv = require("dotenv");
const cors = require('cors');
const connectDB = require("./config/db");
const passport = require("passport");
const errorHandler = require("./middlewares/errorHandler");
const eventRoutes = require("./routes/eventRoutes");
const userRoutes = require("./routes/userRoutes");
dotenv.config();
connectDB();
const app = express();
app.use(cors());
app.use(express.json());
app.use(passport.initialize());
app.use('/uploads', express.static('uploads'));
require("./config/passport")(passport);
app.use("/api/events", eventRoutes);
app.use("/api/users", userRoutes);
app.use(errorHandler);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
module.exports = app;
